name: clean_arc
description: A sample command-line application.
version: 1.0.0
repository: 'https://github.com/Invincible1996/clean_arc.git'

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  dio: any
  intl: ^0.19.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
executables:
  clean_arc:
