name: clean_arc
description: A Clean Architecture generator for Flutter projects
version: 1.0.0
repository: 'https://github.com/Invincible1996/clean_arc.git'

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  path: ^1.8.3
  yaml: ^3.1.2
  dio: ^5.3.3
  logging: ^1.2.0
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1
  meta: ^1.9.1
  collection: ^1.17.2
  analyzer: ^5.13.0
  source_gen: ^1.4.0
  code_builder: ^4.7.0
  dart_style: ^2.3.3

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.9
  mockito: ^5.4.2
  build_runner: ^2.4.6
  json_serializable: ^6.7.1
  freezed: ^2.4.5

executables:
  clean_arc:
